name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env
        # ... other environment variables

    - name: Deploy to server
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > deploy_key
        chmod 600 deploy_key
        scp -i deploy_key .env user@${{ secrets.SERVER_HOST }}:/path/on/server/
        ssh -i deploy_key user@${{ secrets.SERVER_HOST }} "cd /path/on/server && docker-compose build && docker-compose up -d"
      env:
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
